# Generated by Django 4.0.4 on 2022-05-29 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=25)),
                ('Password', models.CharField(max_length=12)),
                ('IsActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField(auto_created=True, default='2020-01-01')),
                ('ProfileImage', models.FileField(default='user.png', upload_to='images/users')),
                ('FullName', models.CharField(default='', max_length=25)),
                ('Gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('City', models.CharField(default='', max_length=25)),
                ('State', models.CharField(default='', max_length=25)),
                ('Pincode', models.CharField(default='', max_length=6)),
                ('Address', models.TextField(default='', max_length=250)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EhApp.master')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
