# Generated by Django 4.0.4 on 2022-05-30 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EhApp', '0002_department'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
