# Generated by Django 4.0.4 on 2022-05-30 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EhApp', '0003_alter_department_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Date', models.DateField(auto_created=True, default='2020-01-01')),
                ('FullName', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=25)),
                ('Gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('Service', models.CharField(choices=[('DC', 'Dental Checkup'), ('FC', 'Fullbody Checkup'), ('ENT', 'ENT Checkup'), ('HC', 'Heart Checkup')], max_length=10)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EhApp.master')),
            ],
        ),
    ]
